version: "3.9"

services:
  benchmark:
    build: .
    image: densenet-bench:latest
    container_name: densenet_benchmark
    command: ["/opt/venv/bin/python", "scripts/densenet_benchmark_all.py", "--output-dir", "/app/results", "--gpu-enabled", "true"]
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - OUTPUT_DIR=/app/results
      - GPU_ENABLED=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tensorboard:
    image: tensorflow/tensorflow:2.17.0
    container_name: tensorboard
    command: tensorboard --logdir=/app/logs/tensorboard --host=0.0.0.0 --port=6006
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6006/"]
      interval: 30s
      timeout: 5s
      retries: 3
